{% set version = "2.9.1" %}
{% set sha256 = "c6160321dc98e6e1184cc791fbeadd2907bb4a0ce0e447f2ea4ff8ab56550913" %}
{% set build_number = "0" %}

package:
  name: pybind11
  version: {{ version }}

source:
  fn: pybind11-{{ version }}.tar.gz
  url: https://github.com/pybind/pybind11/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win32 and py==310] win32 is not being supported going forward.
  number: {{ build_number }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake  >=3.18
    - ninja
  host:
    - python
    - pytest  # [not win32] Testing. (Skipping tests for win32, it's essentially deprecated a deprecated platform.)
    - numpy   # [not win32] testing
    - scipy   # [not win32] testing
    - eigen   # [not (win32 or s390x)]  Testing, update when s390x has eigen.
    - pip
    - setuptools >=42
    - wheel
  run:
    - python

test:
  imports:
    - pybind11
  requires:
    - pip
  commands:
    - test -f ${PREFIX}/share/cmake/pybind11/pybind11Config.cmake                                     # [unix]
    - if exist %LIBRARY_PREFIX%\share\cmake\pybind11\pybind11Config.cmake (exit 0) else (exit 1)      # [win]
    - test -f ${PREFIX}/include/pybind11/pybind11.h                                                   # [unix]
    - if exist %LIBRARY_INC%\pybind11\pybind11.h (exit 0) else (exit 1)                               # [win]
    - test -f $(python -c "import pybind11 as py; print(py.get_include())")/pybind11/pybind11.h       # [unix]
    - if exist $(python -c "import pybind11 as py; print(py.get_include())")\pybind11\pybind11.h (exit 0) else (exit 1)      # [win]
    - pip check

about:
  home: https://github.com/pybind/pybind11/
  license: BSD-3-Clause
  license_family: BSD
  summary: Seamless operability between C++11 and Python
  license_file: LICENSE
  doc_url: https://github.com/pybind/pybind11/blob/master/README.rst
  dev_url: https://github.com/pybind/pybind11/

extra:
  recipe-maintainers:
    - ax3l
    - SylvainCorlay
    - wjakob
