{% set version = "2.9.2" %}
{% set sha256 = "6bd528c4dbe2276635dc787b6b1f2e5316cf6b49ee3e150264e455a0d68d19c1" %}
{% set build_number = "0" %}

package:
  name: pybind11
  version: {{ version }}

source:
  fn: pybind11-{{ version }}.tar.gz
  url: https://github.com/pybind/pybind11/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win32] win32 is a deprecated platform.
  number: {{ build_number }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake  >=3.18
    - ninja
  host:
    - python
    - pip
    - setuptools >=42
    - wheel
    # The following packages are required/desireable for the author's testing:
    - pytest
    - numpy
    - scipy
    - eigen  >=3.2.7
    - libboost >=1.56
  run:
    - python

test:
  # Note: The author's build tests are enabled in the build scripts;
  # however, they do not currently pass and the results of the check
  # are ignored. This should be corrected as time allows.
  imports:
    - pybind11
  requires:
    - pip
  commands:
    - test -f ${PREFIX}/share/cmake/pybind11/pybind11Config.cmake                                     # [unix]
    - if exist %LIBRARY_PREFIX%\share\cmake\pybind11\pybind11Config.cmake (exit 0) else (exit 1)      # [win]
    - test -f ${PREFIX}/include/pybind11/pybind11.h                                                   # [unix]
    - if exist %LIBRARY_INC%\pybind11\pybind11.h (exit 0) else (exit 1)                               # [win]
    - test -f $(python -c "import pybind11 as py; print(py.get_include())")/pybind11/pybind11.h       # [unix]
    - if exist $(python -c "import pybind11 as py; print(py.get_include())")\pybind11\pybind11.h (exit 0) else (exit 1)      # [win]
    - pip check

about:
  home: https://github.com/pybind/pybind11/
  license: BSD-3-Clause
  license_family: BSD
  summary: Seamless operability between C++11 and Python
  license_file: LICENSE
  doc_url: https://github.com/pybind/pybind11/blob/master/README.rst
  dev_url: https://github.com/pybind/pybind11/

extra:
  recipe-maintainers:
    - ax3l
    - SylvainCorlay
    - wjakob
