{% set version = "1.8.1" %}

package:
    name: pybind11
    version: {{ version }}

source:
    fn: pybind11-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/p/pybind11/pybind11-{{ version }}.tar.gz
    md5: 67845d8fd89a1c400dc7c61ccdee14d6

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - pybind11

about:
    home: https://github.com/pybind/pybind11/
    license: BSD 3-Clause
    summary: Seamless operability between C++11 and Python

extra:
  recipe-maintainers:
    - SylvainCorlay
    - wjakob
