{% set version = "2.0.0rc1" %}

package:
    name: pybind11
    version: {{ version }}

source:
    fn: pybind11-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/p/pybind11/pybind11-{{ version }}.tar.gz
    md5: b42aefd6521a1d0fec0ae985519dfb41

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - pybind11

about:
    home: https://github.com/pybind/pybind11/
    license: BSD 3-Clause
    summary: Seamless operability between C++11 and Python

extra:
  recipe-maintainers:
    - SylvainCorlay
    - wjakob
