{% set version = "2.8.1" %}
{% set sha256 = "f1bcc07caa568eb312411dde5308b1e250bd0e1bc020fae855bf9f43209940cc" %}

package:
  name: pybind11
  version: {{ version }}

source:
  fn: pybind11-{{ version }}.tar.gz
  url: https://github.com/pybind/pybind11/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake >=3.18
    - make      # [unix]
    - ninja
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - pybind11
  requires:
    - pip
  commands:
    - test -f ${PREFIX}/share/cmake/pybind11/pybind11Config.cmake                                     # [unix]
    - if exist %LIBRARY_PREFIX%\share\cmake\pybind11\pybind11Config.cmake (exit 0) else (exit 1)      # [win]
    - test -f ${PREFIX}/include/pybind11/pybind11.h      # [unix]
    - if exist %LIBRARY_INC%\pybind11\pybind11.h (exit 0) else (exit 1)      # [win]
    - test -f $(python -c "import pybind11 as py; print(py.get_include())")/pybind11/pybind11.h      # [unix]
    - if exist $(python -c "import pybind11 as py; print(py.get_include())")\pybind11\pybind11.h (exit 0) else (exit 1)      # [win]
    - pip check

about:
  home: https://github.com/pybind/pybind11/
  license: BSD-3-Clause
  license_family: BSD
  summary: Seamless operability between C++11 and Python
  license_file: LICENSE
  doc_url: https://github.com/pybind/pybind11/blob/master/README.rst
  dev_url: https://github.com/pybind/pybind11/

extra:
  recipe-maintainers:
    - ax3l
    - SylvainCorlay
    - wjakob
