travis:
  secure:
    BINSTAR_TOKEN: gHWeDx9R3YhtL4YasScszdSjAJqy0kE5iJ4MnQUln+Q/skdZ7tPXhQhYP9/rint9GEgJzrroDATGovF9jEk/zDEKPy2sStq5wUkTg3h0qM0AusSIQTFdu8j5hDz3HKeXURBTCGwzYKsUI2O8jIVE/X6sAmUk1bKzBltI636Hkd9rP4VZDxCh8UKNqX3/Bk/RUNYFjBjhXu8tBkMdJodyKHvK7lPbRozgi1QTYZuskdpAHE8JY5+d8IwRvgbub3VZUAESwhe1izGOy57iIfsFkxvxfcBbgaQK85+jSNYXlHMaSP2TZLUU7kskW1BrhYvdvvpJZ8eZXT3ex1d6CqctTTSXMxbYN44yE3F4uN+QJGRMmEYnbptruWTZO2MgPED71i88CHbk5dcJcxz4k2RY+wwmwl3TP3wb15j+kPmgTLv2696uU1vthVVvwNPF9YfSZEWgTtcw6cMdEAPz5GT7xwZ2MwhXxm+Uawl2G/WSAUtCXtQBexqzG2OU9ZQUmjC+B2Pgx1ucSJ3DhS5aQHbThhB4MqucVgYaXDyO1SP0mL9tE2dwEBDMIui23dCM4ZANuo4SSQgOVP4aKLXTqVap11tuvOQHjDEmnL0h0Wk+C/6aG7Z++bSd/UloyN+YqL0Y1qSRynh1s5rmHjmJ+ss5hJGgxjwmpKiTbAmxgJXX2B0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
