travis:
  secure:
    BINSTAR_TOKEN: MYT9KVC9yN3ib7xP1GiQ9i8o3MnlxfXaVllN/A+LcZxIM9BoZs09fkxmhK2w6ZkNhj08H0P5tr3YIxSiHsDTKbwRsOKLHMKA3MlJozKvXKAcUE/pG0hSeqbgbxJ+FsyVSnDPN5Q/ICxx/NfZNhiFpOsS98x7qHh9lSEZzpofQBwqE4/jDNM9FBDHXD6Pn7RLIlN1sZwnE5wrbn00H+UyrB4xi0shX+RgNDYkuAOEvNoA/JL/rW3KM4Xjnu5aePume2H8zIoQh/dhb1rrYoGvj0TwAk8Bj5HfyRgTgPYUbrd5ug4Ko9u/KS46s3X+IktBoB4qdlWEfnEKCwYEWPrtvuwQ4fPrDifs75U9qtZWFN/iPf3EPBu6/GqAJuAEWBWzFVSjdtFg3Dce4G8v5jTT1dN2BqhN1e4nRWSHo3LRIOzCi1fWFS9WxvKvrf3Cp93XQ5dFtUB/CQe94+xxWZC4XOp3np76JSXgHDMGGPjt9IgUU+2Nvlcv8o8U3rS0UM+/w8A3CMr6phyuj6vdKh2XwpcMiIM6y+C7Ij/k/hD7y7x08RPO0eGfA9vY0YSWA2dYjYwL5ddU7gFP9Ektu/rV/K+CYShZZBaYCSz8EY0E7wcbpiIT4zRdbrjOouvEbc7karT9Rc+vmh+vmA1VP1rARHd62K2hmXjA39tStD+Q+Og=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
